# Generated by Django 5.1.2 on 2024-10-19 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='image',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='signature',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='signature',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
